### ISSUE TITLE
Xenophon Ten Thousand - Week 1

### ISSUE THREAD

**Issue by ChiaraPalladino** [ChiaraPalladino/furesearch#9]
Just imported the updated file into Recogito, and it looks good to me. Thanks for the cleaning up

I'm going to put .txt files of Books 3, 4, and 1 in the Anabasis folder soon like I did for this file. Even though I won't be annotating them right away, I'll preemptively clean them up the same way you did and put them in there so that you can review them when you've got a chance

**Comment by ChiaraPalladino** [comment]
Update on the preparation: I have added a final document with tagging guidelines, which reflects the current situation in my research group. https://github.com/ChiaraPalladino/furesearch/blob/main/ancient-geographies/annotation-guidelines-english.md 

I have also provided this as a tagset to import in Recogito, to streamline the annotation work. https://github.com/ChiaraPalladino/furesearch/blob/main/ancient-geographies/how-to-use-recogito-tagset.md

**Comment by CianColgan** [comment]
I annotated all of Book 2, and it should be shared with you on Recogito. I didn't actually tag anything yet, since I wanted to make a complete list and do it all at once once you've had a chance to look at it, but I went through and commented what tags I will put on them in order. If you have a chance, let me know if I did the guidelines and nested ones right, especially when it comes to ethnonyms/places referred to within persons' names.

--------------------------------------------------

Also---not urgent---but I also wrote down a list of questions and notes that I need a little help in clarifying or thought you might want to see. Again, no rush, but I wanted to get them to you sooner rather than later:

- How should I tag locations that are not explicitly mentioned by type in the text? Meaning, some places are explicitly called a “town,” “village,” or “large city,” but others are just referred to by name (ex. 2.4.25; Susa and Ecbatana). My guess is that it’s because the ones with no identification were famous enough contemporarily that they didn’t need identification, because who wouldn’t know what they are
     - Should I make a new tag? Something like “uncategorized in text”?
     
- 2.4.25 also has a line that refers to the “bastard brother of Cyrus and Artaxerxes,” but otherwise does not refer to him by name
     - Should I annotate the whole phrase “bastard brother of Cyrus and Artaxerxes” as an individual person, then do nested annotations on 
       “Cyrus” and “Artaxerxes,” tagging them respectively, in order to account for this specific mention of the two proper noun entities?
     - In 2.5.35 there is a similar instance with “Tissaphernes’ brother,” whose name is not mentioned

- I’m going to assume not, but should I tag any mentions of “I”/first-person as Xenophon and person.author?

- In 2.1.2, it says “[...] Damaratus, the Laconian, [...],” should I annotate it all as one person like I would “Xenophon of Athens,” including the comma?

- Every instance of “King” (Artaxerxes II) is capitalized in English, but I took a look at the Greek on Scaife and it’s not capitalized there
     - I assume not, but should I annotate it as I would Artaxerxes? 

- I marked an entity named Cleanor of Orchomenus in 2.5.37 who may be the same person as another Cleanor mentioned earlier, but I’m leaning towards probably not. I put my thinking in the comments of the entity’s annotation, so please look at that and let me know what you think, if my reasoning is sound, etc.-

**Comment by ChiaraPalladino** [comment]
Hi Cian, 

I'm not ignoring this :) I'll add some guidelines on how to establish the boundaries of personal names to the documentation. My research group has determined some criteria that will help. However, in your case we should discuss this between us - you shouldn't find yourself in a position where the annotation strategy that was externally established introduces noise in your data and affects your results. 

More on this soon! And keep this in mind for our next meeting, for sure.

**Comment by CianColgan** [comment]
**Progress Report:**

Well ahead of schedule. I allotted two and a half weeks for annotations, and so far most of the heavy lifting has been done by week one. I did a clean read of book 2-4 for context, then reread them and put in preliminary annotations. I also grabbed encyclopedia entries for these annotations where possible, created a personal annotation guide and project schedule, and created a personal work log. All that's left to do is check them over again upload a complete list of tags, and tag them + add location data where applicable. I also started working on Book 1, but I'm holding off until you can verify to 2-4 annotation system is good, since my first priority with time is fixing and finishing that.

I was hoping that, before I do this, you could take a look at the draft tags in the annotations' comments and tell me if they look good? I commented a sequence of how the tags will work, but didn't actually tag them so that I have to double check them all, and they're easier to change if some are incorrect. 

One big thing I was hoping you could check is that some of the tags for how I refer to nested location annotations are inconsistent, especially in Book 2 and early on, because I was still getting familiar with the annotation system and how to use it. I think I've got a good idea now, though: For location demonyms and ethnonyms (eg. "Xenophon the _Athenian_," "_Persian_ troops," "the _Chalybians_") I use collective.ethnic. (and the personal tag of .region where applicable), but for uses of the city name (eg. "Socrates of _Athens_) I use location.city/town.visited/referenced (city/town and visited/referenced being whatever is applicable).

-----------------------------------------------------------------
**Additional specific questions for books 3-4 (with 2 being in previous comment)**
-4.5.35 has a line about sacrificing a horse to the “Sun-god”, but it isn’t any more specific than that. Is that enough to warrant a person.mythological annotation?
-Starting at 4.7.15, Xenophon mentions the “Scythinians.” I couldn't find anything online with that name specifically. It would seem very likely it’s the Scythians (Similar in Greek: Scythia in Greek is Σκυθικη, and the Greek of this text says Σκυθηνῶν), but I wasn’t totally sure and wanted some extra input
-Not a question, but the Theches mountain where the Ten Thousand famously shouted “Thalatta! Thalatta!” seems to be identified in the modern day, but also some sources said that academics still dispute the exact area, and it’s very difficult without knowing Xenophon’s route. Maybe some viewshed analysis in this section would be helpful?

**Comment by ChiaraPalladino** [comment]
Okay, first things first. I have updated the guidelines with our internal specification on how to decide the boundaries of named entities. This should be very useful. 

In detail regarding your first question: 

> * How should I tag locations that are not explicitly mentioned by type in the text?   
We only use type tags when those types are actually being mentioned in the text. So if there is no type in the text, we don't put a tag. Generic place types are already provided by gazetteers. 

>   * Should I annotate the whole phrase “bastard brother of Cyrus and Artaxerxes” as an individual person, then do nested annotations on “Cyrus” and “Artaxerxes,” tagging them respectively, in order to account for this specific mention of the two proper noun entities?   
The answer to this question (and the one about Tissaphernes' brother) actually depends on two things:   
* Does the brother of Cyrus and Artaxerxes have a name? If yes, then we should annotate the entire string. It would be a good idea here to have a look at the Greek. 
* I would go against nested annotations for now, first because extracted data will look messy, but also because if we want to count all instances of "Cyrus" and "Artaxerxes" we're just going to look them up in the text. 

> * I assumed I should not annotate them, but should I tag any uses of “I”/first-person as xenophon.person.author?    
These things are called **coreferences** and we don't need them for now. This is not that kind of project. 

> * In 2.1.2, it says “[...] Damaratus, the Laconian, [...],” should I annotate it all as one person like I would “Xenophon of Athens,” including the comma?   
This is a good question. I would guess that in the Greek those are not separated by a comma. However, my question is: what do we want to do with those instances? Do we want to know how many times those people are mentioned? Do we want to know how they are named, i.e. with what epithets? This is something to discuss in our meeting.  

> * Every instance of “King” (Artaxerxes II) is capitalized in English, but I took a look at the Greek on Scaife and it’s not capitalized there.  
No need to annotate those for now.

**Comment by ChiaraPalladino** [comment]
**Feedback on the current annotations:**

* First off: if you can give me write access to the Recogito files, I can make some changes and comments locally, so we don't have to track things discoursively here. 
* Instead of using the period to separate tags, just use the normal tags provided by Recogito. It will make things easier for you. (The period is just a convention used in the guidelines) 
* All indications of provenance should be tagged as ethnic, without any further specification of "city". In the Greek, these will probably look like ethnics rather than how they are in English.

**Comment by ChiaraPalladino** [comment]
One more thing: there is no need to have the placename of the annotated entity in the tag (I noticed you have things like "greek.collective.ethnic"). 

We can retrieve placenames easily after we match them with gazetteer entries: later, when we search for "Athens", we will be able to find all the ways in which Athens is mentioned. 
For people, however, a tag with the authoritative form of the name is necessary because we don't have a gazetteer. So, the first tag for every person should be their name (and make sure to always use the same tag for every occurrence, of course).

**Comment by CianColgan** [comment]
Ok awesome, I know I had a lot of stuff, so thanks for looking them over! I'll go ahead and start revising.

I should've clarified, the reason why I annotated the place names with a tag of their name (and the people too for that matter) is because I'm trying to link an encyclopedia entry to each entity I can, so that name is like the proxy I attach the link to, rather than just having a whole link in the tags.
